
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x80\x98\x89\x82hgca\x8e\x92\x88\xee\xc9< \xc3'
    
_lr_action_items = {'H2':([0,11,],[2,2,]),'H3':([0,11,],[3,3,]),'H1':([0,11,],[4,4,]),'TEXT':([2,3,4,],[7,7,7,]),'CR':([5,6,7,8,9,10,12,],[11,-2,-7,-5,-6,-4,-3,]),'$end':([1,5,6,7,8,9,10,12,],[0,-1,-2,-7,-5,-6,-4,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,],[1,]),'expression':([0,11,],[6,12,]),'statement':([0,],[5,]),'factor':([2,3,4,],[8,9,10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> body","S'",1,None,None,None),
  ('body -> statement','body',1,'p_body','/Users/globit/git/SSE-Compiling-Course/ProjectTemplate/sample/part/mkyacc.py',13),
  ('statement -> expression','statement',1,'p_state','/Users/globit/git/SSE-Compiling-Course/ProjectTemplate/sample/part/mkyacc.py',17),
  ('statement -> statement CR expression','statement',3,'p_state','/Users/globit/git/SSE-Compiling-Course/ProjectTemplate/sample/part/mkyacc.py',18),
  ('expression -> H1 factor','expression',2,'p_exp_cr','/Users/globit/git/SSE-Compiling-Course/ProjectTemplate/sample/part/mkyacc.py',25),
  ('expression -> H2 factor','expression',2,'p_exp_cr','/Users/globit/git/SSE-Compiling-Course/ProjectTemplate/sample/part/mkyacc.py',26),
  ('expression -> H3 factor','expression',2,'p_exp_cr','/Users/globit/git/SSE-Compiling-Course/ProjectTemplate/sample/part/mkyacc.py',27),
  ('factor -> TEXT','factor',1,'p_factor_text','/Users/globit/git/SSE-Compiling-Course/ProjectTemplate/sample/part/mkyacc.py',31),
]
